apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::982065454085:role/regular-eks-node-group-20240710174825782800000001
      username: system:node:{{EC2PrivateDNSName}}

    - rolearn: arn:aws:iam::982065454085:role/prod-ci
      username: user
      groups:
      - system:masters

kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system