apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: btc22
  name: btc22
  namespace: btc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: btc22
  template:
    metadata:
      labels:
        app: btc22
    spec:
      containers:
      - image: 982065454085.dkr.ecr.us-east-2.amazonaws.com/btc22:{{version}}
        name: btc
        args:
        - -datadir=/app/data
        - -prune=550

        volumeMounts:
        - mountPath: "/app/data"
          name: btc-pvc
        resources:
          requests:
            cpu: 450m
            memory: 500Mi
          limits:
            cpu: 1

      volumes:
      - name: btc-pvc
        persistentVolumeClaim:
          claimName: btc-pvc

status: {}
