apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: btc-pvc
  namespace: btc
spec:
  storageClassName: ebs-sc # Empty string must be explicitly set otherwise default StorageClass will be set
  resources:
    requests:
      storage: 8Gi
  accessModes:
    - ReadWriteOnce