name: Docker Image CI

on:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - feat
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    

jobs:
  build:
    permissions:
      id-token: write # This is required for requesting the JWT for authing into aws via OIDC
      contents: read
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set output
      id: vars
      run: echo "tag=${{  github.ref_name }}" >> $GITHUB_OUTPUT
    - name: Build the Docker image
      working-directory: ./btc22
      run: bash build.sh ${{  github.ref_name }}
    - uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-east-2
        role-to-assume: prod-ci
    - name: Push to ECR
      working-directory: ./btc22
      run: bash tag_push_ecr.bash ${{  github.ref_name }}
