name: Docker Image CI

on:
  push:
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [ "main" ]
  workflow_run:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set output
      id: vars
      run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
    - name: Check output
      env:
        RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
    - name: Build the Docker image
      run: ./btc22/build.sh ${{ steps.vars.outputs.tag }}

